# Generated by Django 5.2.6 on 2025-10-26 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField()),
                ('duracion_semanas', models.IntegerField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estudiantes', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nombre_curso'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_material', models.CharField(max_length=150)),
                ('tipo_material', models.CharField(max_length=100)),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('en_stock', models.IntegerField()),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.CASCADE, related_name='materiales_requeridos', to='app_curso.curso')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'unique_together': {('nombre_material', 'id_curso')},
            },
        ),
    ]
