# Generated by Django 5.2.6 on 2025-10-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_curso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='cursos'),
        ),
    ]
